### ISSUE TITLE
Some things seems outdated

### ISSUE THREAD

**Issue by Labzz** [ianperrin/MMM-Formula1#9]
Hi i noticed that Max Verstappen still drive for Torro Rosso (in the calendar), while he already drive nearly a half year for Red bull, is there an option to update things like these? or will it be updated the next race season ?!

**Comment by ianperrin** [comment]
Hi @Labzz 

Good pickup. The data from the api was actually correct, but the module wasn't correctly handling the situation where a driver has driven for multiple teams in one season.

This should be fixed now so that in the current (2016) season both constructors are shown for Max Verstappen and Daniil Kvyat. 

Next season, the constructor teams should update to reflect any teams movements etc

Thanks for the report and please let me know if there are still issues

Ian

**Comment by Labzz** [comment]
Thanks for the quick reply and fix.
